### ISSUE TITLE
Remeha thermostaat - maximum retries exceeded

### ISSUE THREAD

**Issue by tomds25** [tuk90/RemehaHome-Domoticz#20]
Hi, installed Remeha plugin on Domoticz. Worked fine, but after some requests I get below error in log:

Error: Remeha thermostaat: Error making GET request: HTTPSConnectionPool(host='api.bdrthermea.net', port=443): Max retries exceeded with url: /Mobile/api/homes/dashboard (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x3746AA10>: Failed to resolve 'api.bdrthermea.net' ([Errno 11001] getaddrinfo failed)"))

when changing poll interval to 5 minutes i get below errors in log and plugin does not work at all anymore:

2024-02-25 12:35:16.202 Error: Remeha thermostaat: (RemehaHome) failed to load 'plugin.py', Python Path used was 'C:\Program Files (x86)\Domoticz\plugins\RemehaHome-Domoticz\;C:\Program Files (x86)\Python37-32\python37.zip;C:\Program Files (x86)\Python37-32\Lib\;C:\Program Files (x86)\Python37-32\DLLs\;C:\Program Files (x86)\Domoticz;C:\Program Files (x86)\Python37-32;C:\Program Files (x86)\Python37-32\lib\site-packages'.
2024-02-25 12:35:16.213 Error: Remeha thermostaat: Traceback (most recent call last):
2024-02-25 12:35:16.228 Error: Remeha thermostaat: File "C:\Program Files (x86)\Domoticz\plugins\RemehaHome-Domoticz\plugin.py", line 23, in <module>
2024-02-25 12:35:16.228 Error: Remeha thermostaat: import requests
2024-02-25 12:35:16.228 Error: Remeha thermostaat: File "C:\Program Files (x86)\Python37-32\lib\site-packages\requests\__init__.py", line 48, in <module>
2024-02-25 12:35:16.229 Error: Remeha thermostaat: from charset_normalizer import __version__ as charset_normalizer_version
2024-02-25 12:35:16.229 Error: Remeha thermostaat: File "C:\Program Files (x86)\Python37-32\lib\site-packages\charset_normalizer\__init__.py", line 24, in <module>
2024-02-25 12:35:16.229 Error: Remeha thermostaat: from .api import from_bytes, from_fp, from_path, is_binary
2024-02-25 12:35:16.229 Error: Remeha thermostaat: File "C:\Program Files (x86)\Python37-32\lib\site-packages\charset_normalizer\api.py", line 5, in <module>
2024-02-25 12:35:16.229 Error: Remeha thermostaat: from .cd import (
2024-02-25 12:35:16.229 Error: Remeha thermostaat: File "C:\Program Files (x86)\Python37-32\lib\site-packages\charset_normalizer\cd.py", line 14, in <module>
2024-02-25 12:35:16.230 Error: Remeha thermostaat: from .md import is_suspiciously_successive_range
2024-02-25 12:35:16.230 Error: Remeha thermostaat: SystemError: initialization of md__mypyc did not return an extension module

what I'm I doing wrong? what is max number of requests that can be done towards api.bdrthermea.net'?

Domoticz is running on Windows in my case.

Kind regards

Tom

**Comment by tuk90** [comment]
Ps. Are you in the newest version?

**Comment by tuk90** [comment]
Version of the plugin
