### ISSUE TITLE
Remeha Home hardware (34) thread seems to have ended unexpectedly

### ISSUE THREAD

**Issue by infoedkok** [tuk90/RemehaHome-Domoticz#22]
Hi,
Thank you for your great work on this plugin! I installed it  in a docker implementation.

It worked for a very short time (I could set the setpoint).

But after some minutes the devices where not updated anymore and I got this errors in the domoticz log.

Any idea where to look first?

Regards Ed

2024-10-14 17:22:01.572 Error: Remeha Home: (RemehaHome) failed to load 'plugin.py', Python Path used was '/opt/domoticz/userdata/plugins/RemehaHome-Domoticz/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2024-10-14 17:22:01.574 Error: Remeha Home: Traceback (most recent call last):
2024-10-14 17:22:01.574 Error: Remeha Home: File "/usr/local/lib/python3.9/dist-packages/requests/compat.py", line 11, in <module>
2024-10-14 17:22:01.575 Error: Remeha Home: import chardet
2024-10-14 17:22:01.575 Error: Remeha Home: ModuleNotFoundError: No module named 'chardet'
2024-10-14 17:22:01.575 Error: Remeha Home:
2024-10-14 17:22:01.575 Error: Remeha Home: During handling of the above exception, another exception occurred:
2024-10-14 17:22:01.575 Error: Remeha Home:
2024-10-14 17:22:01.575 Error: Remeha Home: Traceback (most recent call last):
2024-10-14 17:22:01.575 Error: Remeha Home: File "/opt/domoticz/userdata/plugins/RemehaHome-Domoticz/plugin.py", line 23, in <module>
2024-10-14 17:22:01.575 Error: Remeha Home: import requests
2024-10-14 17:22:01.575 Error: Remeha Home: File "/usr/local/lib/python3.9/dist-packages/requests/__init__.py", line 45, in <module>
2024-10-14 17:22:01.575 Error: Remeha Home: from .exceptions import RequestsDependencyWarning
2024-10-14 17:22:01.575 Error: Remeha Home: File "/usr/local/lib/python3.9/dist-packages/requests/exceptions.py", line 9, in <module>
2024-10-14 17:22:01.575 Error: Remeha Home: from .compat import JSONDecodeError as CompatJSONDecodeError
2024-10-14 17:22:01.575 Error: Remeha Home: File "/usr/local/lib/python3.9/dist-packages/requests/compat.py", line 13, in <module>
2024-10-14 17:22:01.575 Error: Remeha Home: import charset_normalizer as chardet
2024-10-14 17:22:01.575 Error: Remeha Home: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
2024-10-14 17:22:01.575 Error: Remeha Home: from .api import from_bytes, from_fp, from_path, is_binary
2024-10-14 17:22:01.575 Error: Remeha Home: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/api.py", line 5, in <module>
2024-10-14 17:22:01.575 Error: Remeha Home: from .cd import (
2024-10-14 17:22:01.575 Error: Remeha Home: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/cd.py", line 14, in <module>
2024-10-14 17:22:01.575 Error: Remeha Home: from .md import is_suspiciously_successive_range
2024-10-14 17:22:01.575 Error: Remeha Home: AttributeError: PyCapsule_Import "charset_normalizer.md__mypyc.init_charset_normalizer___md" is not valid
2024-10-14 17:23:02.415 Error: Remeha Home hardware (34) thread seems to have ended unexpectedly

**Comment by infoedkok** [comment]
Looked like I solved it myself: ran the command "pip install -U charset" to the specific docker id.
Installed chardet.
Gave me some other errors, but after restarting the domoticz container, the devices are now updating.

**Comment by infoedkok** [comment]
No, not all devices are updated. The following are NOT:
- EnergyConsumption
- EnergyDelivered
- dhwTemperature

**Comment by tuk90** [comment]
Why not, any errors? Energy consumption and energy delivered are only updated once an hour and if Remeha is not updating them they will not be updated. So check again tomorrow. Regarding dhwtemperature do you have a cv or a heat pump?

**Comment by infoedkok** [comment]
You're absolutely right!
Than you for this explanation.

Checked the first two devices and they are updated. 
The last one can not be updated in my system since my heat pump does not provide the dhw, my cv does that .

Succes, case closed ;-)

Keep up the good work!
